name: Docs
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
          package_json_file: ./docs/package.json
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: "pnpm"
          cache-dependency-path: ./docs/pnpm-lock.yaml
      - name: Install dependencies
        working-directory: ./docs
        run: pnpm install
      - name: Build
        working-directory: ./docs
        run: pnpm run build
      - name: Upload static files
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
